<?php
/**
 * CapacityType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MehrIt\AmazonSellingPartner
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MehrIt\AmazonSellingPartner\Model\Services;
use \MehrIt\AmazonSellingPartner\ObjectSerializer;
use \MehrIt\AmazonSellingPartner\ModelInterface;

/**
 * This class was auto-generated by https://github.com/OpenAPITools/openapi-generator/.
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 */
class CapacityType
{
    /**
     * Possible values of this enum
     */
    const SCHEDULED_CAPACITY = 'SCHEDULED_CAPACITY';

    const AVAILABLE_CAPACITY = 'AVAILABLE_CAPACITY';

    const ENCUMBERED_CAPACITY = 'ENCUMBERED_CAPACITY';

    const RESERVED_CAPACITY = 'RESERVED_CAPACITY';

    private string $value;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SCHEDULED_CAPACITY,
            self::AVAILABLE_CAPACITY,
            self::ENCUMBERED_CAPACITY,
            self::RESERVED_CAPACITY
        ];
    }

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function toString(): string
    {
        return $this->value;
    }
}

