generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: MehrIt\AmazonSellingPartner
  srcBasePath: src/MehrIt/AmazonSellingPartner
  modelPackage: Model\Notifications
  packageName: Notifications
files:
  api.mustache:
    templateType: API
    destinationFilename: /NotificationsSDK.php
