generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: MehrIt\AmazonSellingPartner
  srcBasePath: src/MehrIt/AmazonSellingPartner
  modelPackage: Model\Sales
  packageName: Sales
files:
  api.mustache:
    templateType: API
    destinationFilename: /SalesSDK.php
