generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: MehrIt\AmazonSellingPartner
  srcBasePath: src/MehrIt/AmazonSellingPartner
  modelPackage: Model\Reports
  packageName: Reports
  useTags: false
files:
  api.mustache:
    templateType: API
    destinationFilename: /ReportsSDK.php
