generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: MehrIt\AmazonSellingPartner
  srcBasePath: src/MehrIt/AmazonSellingPartner
  modelPackage: Model\FBASmallAndLight
  packageName: FBASmallAndLight
files:
  api.mustache:
    templateType: API
    destinationFilename: /FBASmallAndLightSDK.php
