generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: MehrIt\AmazonSellingPartner
  srcBasePath: src/MehrIt/AmazonSellingPartner
  modelPackage: Model\Orders
  packageName: Orders
  useTags: false
  className: Orders
files:
  api.mustache:
    templateType: API
    destinationFilename: /OrdersSDK.php
