generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: MehrIt\AmazonSellingPartner
  srcBasePath: src/MehrIt/AmazonSellingPartner
  modelPackage: Model\Shipping
  packageName: Shipping
files:
  api.mustache:
    templateType: API
    destinationFilename: /ShippingSDK.php
