generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: MehrIt\AmazonSellingPartner
  srcBasePath: src/MehrIt/AmazonSellingPartner
  modelPackage: Model\FulfillmentInbound
  packageName: FulfillmentInbound
files:
  api.mustache:
    templateType: API
    destinationFilename: /FulfillmentInboundSDK.php
